/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.RegisterParentRole;

import Business.EcoSystem;
import Business.Enterprise.AdoptionEnterprise;
import Business.Organization.RegisterParentOrganization;
import Business.ProspectiveParent.ProspectiveParent;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kinnari
 */
public class RegisterParent1JPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterParent1JPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private RegisterParentOrganization organization;
    private AdoptionEnterprise enterprise;
    private EcoSystem business;
    public RegisterParent1JPanel(JPanel userProcessContainer, UserAccount account, RegisterParentOrganization organization, AdoptionEnterprise enterprise, EcoSystem busines) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = busines;
        populateRadioButtons();
        validate();
        
    }
    public void validate(){
        
        txtParent1Age.addKeyListener(new KeyAdapter() {
                public void keyTyped(KeyEvent e) {
                    
                    char vChar = e.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE))) {
                        
                       e.consume();
                    }
               
                }
            });
        
        txtParent2Age.addKeyListener(new KeyAdapter() {
                public void keyTyped(KeyEvent e) {
                    
                    char vChar = e.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE))) {
                        
                       e.consume();
                    }
               
                }
            });
        
        
        txtFieldTotalIncome1.addKeyListener(new KeyAdapter() {
                public void keyTyped(KeyEvent e) {
                    
                    char vChar = e.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE))) {
                        
                       e.consume();
                    }
               
                }
            });
    }
    public void populateRadioButtons(){
        
        ButtonGroup groupFather = new ButtonGroup();
        groupFather.add(radioBtnNoFather);
        groupFather.add(radioBtnYesFather);
        
        ButtonGroup groupMOther = new ButtonGroup();
        groupMOther.add(radioBtnYesMother);
        groupMOther.add(radioBtnNoMother);
        
        ButtonGroup crime = new ButtonGroup();
        crime.add(radioBtncriminalNo);
        crime.add(radioBtncriminalYes);
        
        ButtonGroup disease1 = new ButtonGroup();
        disease1.add(radioBtnCarrierNo);
        disease1.add(radioBtnCarrierYes);
        
        ButtonGroup disease2 = new ButtonGroup();
        disease2.add(radioBtnDiseaseNo);
        disease2.add(radioBtnDiseaseYes);
        
        ButtonGroup disease3 = new ButtonGroup();
        disease3.add(radioBtnillnessNo);
        disease3.add(radioBtnillnessYes);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radioBtnYesMother = new javax.swing.JRadioButton();
        radioBtnNoFather = new javax.swing.JRadioButton();
        radioBtnYesFather = new javax.swing.JRadioButton();
        radioBtnNoMother = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtFieldMotherQualifications = new javax.swing.JTextField();
        txtFieldFatherQualifications = new javax.swing.JTextField();
        txtFieldAccomplishments = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFieldFatherOccupation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFieldMotherOccupation = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFieldCrime = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtParent1 = new javax.swing.JTextField();
        txtParent2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtParent1Age = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtParent2Age = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        radioBtnCarrierYes = new javax.swing.JRadioButton();
        radioBtnCarrierNo = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        radioBtnillnessYes = new javax.swing.JRadioButton();
        radioBtnillnessNo = new javax.swing.JRadioButton();
        radioBtncriminalYes = new javax.swing.JRadioButton();
        radioBtncriminalNo = new javax.swing.JRadioButton();
        radioBtnDiseaseYes = new javax.swing.JRadioButton();
        radioBtnDiseaseNo = new javax.swing.JRadioButton();
        txtFieldTotalIncome1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtSSN1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtSSN2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        childAgejComboBox = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Education Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 547, 32));

        jLabel2.setText("Mother qualifications :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 170, 35));

        jLabel3.setText("Father qualifications :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 171, 34));

        jLabel4.setText("Any accomplishments :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 171, 36));

        jLabel5.setText("Has the Father graduated? ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 194, 30));

        radioBtnYesMother.setText("Yes");
        jPanel1.add(radioBtnYesMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        radioBtnNoFather.setText("No");
        jPanel1.add(radioBtnNoFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        radioBtnYesFather.setText("Yes");
        jPanel1.add(radioBtnYesFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        radioBtnNoMother.setText("No");
        jPanel1.add(radioBtnNoMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        jLabel6.setText("Has the Mother graduated? ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 165, 30));
        jPanel1.add(txtFieldMotherQualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 259, 35));
        jPanel1.add(txtFieldFatherQualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 259, 35));
        jPanel1.add(txtFieldAccomplishments, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 259, 40));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1330, -1, -1));

        jLabel7.setText("Father occupation :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 201, 34));
        jPanel1.add(txtFieldFatherOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 200, 34));

        jLabel8.setText("Mother occupation :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 201, 28));
        jPanel1.add(txtFieldMotherOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, 200, 36));

        jLabel9.setText("If any one of the parent has been found guilty, please click yes. If you answered yes, please explain :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1040, 440, 29));
        jPanel1.add(txtFieldCrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1080, 820, 35));

        btnSubmit.setText("Submit >>");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 960, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" Information for Criminal Check ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 760, 640, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Personal Details");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 497, -1));

        jLabel12.setText("Prospective Parent1:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 135, 34));

        jLabel13.setText("Prospectve Parent2 :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 150, 50));

        txtParent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParent1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtParent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 193, 34));

        txtParent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParent2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtParent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 193, 34));

        jLabel14.setText("Parent1 age :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 135, 26));

        txtParent1Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParent1AgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtParent1Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 193, 35));

        jLabel15.setText("Parent2 age :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 135, 33));
        jPanel1.add(txtParent2Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 193, 33));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(" Medical Details");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1130, 547, -1));

        jLabel17.setText("(1) Have you personally or ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 820, 190, 20));

        jLabel18.setText("ever pled guilty to or being convicted  or found guilty of misdemeanor in any U.S. or non-U.S. or military court which involves : ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 880, 640, 20));

        jLabel19.setText("(2) has any entity of which you were a  principal at the time of activities ocurred");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 850, 460, 20));

        jLabel20.setText("• embezzlement, theft, extortion, fraud, fraudulent conversion, forgery, counterfeiting, false pretenses, ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 900, 630, 20));

        jLabel21.setText(" bribery, gambling, racketeering or misappropriation of funds, securities or property;");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 920, 530, -1));

        jLabel22.setText("• violation of sections 7203, 7204, 7205 or 7207 of the Internal Revenue Code of 1986;or ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 940, 590, -1));

        jLabel23.setText("• violation of sections 152. 1341, 1342, or 1343 or chapters 25. 4 7, 95 or 96 of the U.S. Criminal Code; or ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 960, 620, -1));

        jLabel24.setText("• any transaction in or advice concerning futures, options, leverage transactions or securities? ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 980, 540, -1));

        radioBtnCarrierYes.setText("Yes");
        jPanel1.add(radioBtnCarrierYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 1210, -1, -1));

        radioBtnCarrierNo.setText("No");
        jPanel1.add(radioBtnCarrierNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 1210, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(" Financial Details");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 547, 40));

        jLabel26.setText("Have you ever been told that you are a carrier of a genetic/inherited disease? ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1210, 450, 20));

        jLabel27.setText("Have you had any major illness? ");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1190, 220, 20));

        jLabel28.setText("Have you ever been told that you have a genetic/inherited disease? ");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1230, 390, 20));

        radioBtnillnessYes.setText("Yes");
        radioBtnillnessYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnillnessYesActionPerformed(evt);
            }
        });
        jPanel1.add(radioBtnillnessYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 1180, -1, -1));

        radioBtnillnessNo.setText("No");
        jPanel1.add(radioBtnillnessNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 1180, -1, -1));

        radioBtncriminalYes.setText("Yes");
        radioBtncriminalYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtncriminalYesActionPerformed(evt);
            }
        });
        jPanel1.add(radioBtncriminalYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1010, -1, -1));

        radioBtncriminalNo.setText("No");
        jPanel1.add(radioBtncriminalNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1010, -1, -1));

        radioBtnDiseaseYes.setText("Yes");
        jPanel1.add(radioBtnDiseaseYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 1240, -1, -1));

        radioBtnDiseaseNo.setText("No");
        jPanel1.add(radioBtnDiseaseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 1240, -1, -1));
        jPanel1.add(txtFieldTotalIncome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 710, 200, 35));

        jLabel29.setText("Total income from all the sources :");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, -1, 29));

        jLabel30.setText("If you answered yes to any of the above questions, please submit medical reports at the nearest department ");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1280, 630, -1));

        jLabel31.setText("SSN");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));

        txtSSN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSN1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtSSN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 150, -1));

        jLabel32.setText("SSN");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, -1));

        txtSSN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSN2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtSSN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 150, -1));

        jLabel33.setText("Email ID : ");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 135, 33));

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 190, -1));

        jLabel34.setText("Child Age : ");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, -1));

        childAgejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1-5", "6-10", ">10" }));
        childAgejComboBox.setSelectedIndex(-1);
        jPanel1.add(childAgejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 120, -1));

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public static void  sendEmail(String from, String password, String to, String sub, String msg) {

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class",
                "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");
        //get Session   
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication(from, password);
            }
        });
        //compose message    
        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setSubject(sub);
            message.setText(msg);
            //send message  
            javax.mail.Transport.send(message);
            System.out.println("message sent successfully");
        } catch (javax.mail.MessagingException e) {
            throw new RuntimeException(e);
        }

    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String parent1 = txtParent1.getText();
        String parent2 = txtParent2.getText();
        int age1 = Integer.parseInt(txtParent1Age.getText());
        int age2 = Integer.parseInt(txtParent2Age.getText());
        String motherQualification = txtFieldMotherQualifications.getText();
        String fatherQualification = txtFieldFatherQualifications.getText();
        String accomplishments = txtFieldAccomplishments.getText();
        String fatherOccupation = txtFieldFatherOccupation.getText();
        String motherOccupation = txtFieldMotherOccupation.getText();
        Double totalIncome = Double.parseDouble(txtFieldTotalIncome1.getText());
        String SSN1 = txtSSN1.getText();
        String SSN2 = txtSSN2.getText();
        String email = txtEmailId.getText();
        String childAge = childAgejComboBox.getSelectedItem().toString();
        String adoptionStatus = ProspectiveParent.REGISTERED;
        

        ProspectiveParent parent = enterprise.getProspectiveParentDirectory().addParent();
        parent.setParent1(parent1);
        parent.setParent2(parent2);
        parent.setParent1Age(age1);
        parent.setParent2Age(age2);
        parent.setMotherQualification(motherQualification);
        parent.setFatherQualification(fatherQualification);
        parent.setAccomplishments(accomplishments);
        parent.setFatherOccupation(fatherOccupation);
        parent.setMotherOccupation(motherOccupation);
        parent.setTotalIncome(totalIncome);
        parent.setParent1SSN(SSN1);
        parent.setParent2SSN(SSN2);
        parent.setEmailId(email);
        parent.setChildAge(childAge);
        parent.setAdoptionStatus(adoptionStatus);

        if(radioBtnYesFather.isSelected())
        {
            boolean fatherGraduated = true;
            parent.setFather_graduated(fatherGraduated);
            radioBtnNoFather.setSelected(false);
        }
        else if (radioBtnNoFather.isSelected())
        {
            boolean fatherGraduated = false;
            parent.setFather_graduated(fatherGraduated);
            radioBtnYesFather.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select yes or no");
            return;
        }

        if(radioBtnYesMother.isSelected())
        {
            boolean motherGraduated = true;
            parent.setMother_graduated(motherGraduated);
            radioBtnNoMother.setSelected(false);
        }
        else if (radioBtnNoMother.isSelected())
        {
            boolean motherGraduated = false;
            parent.setMother_graduated(motherGraduated);
            radioBtnYesMother.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select yes or no");
            return;
        }

        if(radioBtncriminalYes.isSelected())
        {
            boolean crime1 = true;
            parent.setCrime(crime1);
            radioBtncriminalNo.setSelected(false);

            String crime = txtFieldCrime.getText();

        }
        else if (radioBtncriminalNo.isSelected())
        {
            boolean crime1 = false;
            parent.setCrime(crime1);
            radioBtncriminalYes.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select yes or no");
            return;
        }

        if(radioBtnillnessYes.isSelected())
        {
            boolean illness = true;
            parent.setIllness(illness);
            radioBtnillnessNo.setSelected(false);
        }
        else if (radioBtnillnessNo.isSelected())
        {
            boolean illness = false;
            parent.setIllness(illness);
            radioBtnillnessYes.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select yes or no");
            return;
        }

        if(radioBtnCarrierYes.isSelected())
        {
            boolean carrier = true;
            parent.setCarrierGenetic(carrier);
            radioBtnCarrierNo.setSelected(false);
        }
        else if (radioBtnCarrierNo.isSelected())
        {
            boolean illness = false;
            parent.setIllness(illness);
            radioBtnCarrierYes.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select yes or no");
            return;
        }

        if(radioBtnDiseaseYes.isSelected())
        {
            boolean genetic = true;
            parent.setGenetic(genetic);
            radioBtnDiseaseNo.setSelected(false);
        }
        else if (radioBtnDiseaseNo.isSelected())
        {
            boolean illness = false;
            parent.setIllness(illness);
            radioBtnDiseaseYes.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select yes or no");
            return;
        }

        JOptionPane.showMessageDialog(null, "parent created");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtParent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParent1ActionPerformed

    private void txtParent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParent2ActionPerformed

    private void txtParent1AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParent1AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParent1AgeActionPerformed

    private void radioBtnillnessYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnillnessYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnillnessYesActionPerformed

    private void radioBtncriminalYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtncriminalYesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_radioBtncriminalYesActionPerformed

    private void txtSSN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSN1ActionPerformed

    private void txtSSN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSN2ActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> childAgejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioBtnCarrierNo;
    private javax.swing.JRadioButton radioBtnCarrierYes;
    private javax.swing.JRadioButton radioBtnDiseaseNo;
    private javax.swing.JRadioButton radioBtnDiseaseYes;
    private javax.swing.JRadioButton radioBtnNoFather;
    private javax.swing.JRadioButton radioBtnNoMother;
    private javax.swing.JRadioButton radioBtnYesFather;
    private javax.swing.JRadioButton radioBtnYesMother;
    private javax.swing.JRadioButton radioBtncriminalNo;
    private javax.swing.JRadioButton radioBtncriminalYes;
    private javax.swing.JRadioButton radioBtnillnessNo;
    private javax.swing.JRadioButton radioBtnillnessYes;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFieldAccomplishments;
    private javax.swing.JTextField txtFieldCrime;
    private javax.swing.JTextField txtFieldFatherOccupation;
    private javax.swing.JTextField txtFieldFatherQualifications;
    private javax.swing.JTextField txtFieldMotherOccupation;
    private javax.swing.JTextField txtFieldMotherQualifications;
    private javax.swing.JTextField txtFieldTotalIncome1;
    private javax.swing.JTextField txtParent1;
    private javax.swing.JTextField txtParent1Age;
    private javax.swing.JTextField txtParent2;
    private javax.swing.JTextField txtParent2Age;
    private javax.swing.JTextField txtSSN1;
    private javax.swing.JTextField txtSSN2;
    // End of variables declaration//GEN-END:variables
}
